### ISSUE TITLE
Something doesn't work

### ISSUE THREAD

**Issue by harl** [Sav22999/all-currencies#2]
Greetings.
I'm unable to get this add-on to work properly.  When I click on the toolbar button, the various currency symbols are shown in a smaller frame, but clicking on any of these symbols doesn't copy it.

I've tried clicking and double-clicking them with the left/middle/right mouse button, but they don't get copied.
I've tried to copy via Ctrl+C after clicking.
The right-click context menu has no Copy action either.

(Firefox 122.0.1, Windows 11)

**Comment by Sav22999** [comment]
@harl HI! I'm sorry for this inconvenience.
I'll check this issue tomorrow, thanks for the reporting 😄

**Comment by Sav22999** [comment]
@harl I've fixed the bug, the 1.1.1 release should work correctly now 😄 
Thanks again for the reporting!

**Comment by harl** [comment]
Thank YOU for fixing it so quickly! 👍🏻
